# Generated by Django 4.0.1 on 2022-01-17 09:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Заголовок страницы')),
                ('subtitle', models.CharField(default='', max_length=100, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Настройки новостной страницы',
                'verbose_name_plural': 'Настройки новостной страницы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(default='', verbose_name='Краткое описание')),
                ('icon', models.ImageField(upload_to='category_icons', verbose_name='Иконка 48x48')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', verbose_name='Тег')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120, verbose_name='Заголовок публикации')),
                ('subtitle', models.TextField(default='', verbose_name='Подзаголовок')),
                ('published', models.DateField(default=datetime.date(2022, 1, 17), verbose_name='Дата публикации')),
                ('text', models.TextField(verbose_name='Основная статья')),
                ('meta_keywords', models.TextField(default='', verbose_name='Ключевые слова (метаданные)')),
                ('meta_description', models.TextField(verbose_name='Описание (метаданные)')),
                ('meta_author', models.TextField(default='l1ghth4t', verbose_name='Автор (метаданные)')),
                ('meta_copyright', models.TextField(default='Alexey Pirogov', verbose_name='Авторские права (метаданные)')),
                ('category', models.ManyToManyField(to='articles.Category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(to='articles.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
