# Generated by Django 4.0.1 on 2022-01-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='disclaimer',
            field=models.TextField(default='none', verbose_name='disclaimer'),
        ),
    ]
