# Generated by Django 4.0.1 on 2022-01-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='background_image',
            field=models.ImageField(default='', upload_to='article_bgs/', verbose_name='Фоновое изображение'),
        ),
        migrations.AddField(
            model_name='article',
            name='poster_image',
            field=models.ImageField(default='', upload_to='article_posters/', verbose_name='Изображение-постер'),
        ),
        migrations.AddField(
            model_name='article',
            name='poster_image_check',
            field=models.BooleanField(default=False, verbose_name='Использовать изображение-постер'),
        ),
    ]
