# Generated by Django 4.0.1 on 2022-01-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_poster_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contents',
            field=models.TextField(default='<li><a href="#link">Paragraphs</a><ul><li><a href="#link">Lead Paragraphs</a></li></ul></li>', verbose_name='Оглавление'),
        ),
    ]
