# Generated by Django 4.0.1 on 2022-01-27 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contents',
            field=models.TextField(default='<li><a href="#content">Ссылка на главный заголовок</a><ul><li><a href="#link">Заголовок в статье</a></li><ul><li><a href="#link">Подзаголовок</a></li></ul></ul></li>', verbose_name='Оглавление'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateField(default=datetime.date(2022, 1, 27), verbose_name='Дата публикации'),
        ),
    ]
