# Generated by Django 4.0.2 on 2022-02-08 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_contents_alter_article_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateField(default=datetime.date(2022, 2, 8), verbose_name='Дата публикации'),
        ),
    ]
