# Generated by Django 4.0.1 on 2022-01-17 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Заголовок')),
                ('icon', models.CharField(default='', max_length=40, verbose_name='Имя иконки в фреймворке')),
                ('tooltip', models.CharField(default='', max_length=50, verbose_name='Всплывающая подсказка')),
                ('link', models.CharField(default='', max_length=50, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Иконка меню',
                'verbose_name_plural': 'Иконки меню',
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Заголовок')),
                ('icon', models.CharField(default='', max_length=40, verbose_name='Имя иконки в фреймворке')),
                ('text', models.CharField(default='', max_length=100, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Строчка',
                'verbose_name_plural': 'Личные данные',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Заголовок')),
                ('subtitle', models.CharField(default='', max_length=100, verbose_name='Подзаголовок')),
                ('quote', models.TextField(default='', verbose_name='Цитата')),
                ('author', models.CharField(default='', max_length=70, verbose_name='Автор цитаты')),
                ('avatar', models.ImageField(upload_to='main_page/', verbose_name='Аватар')),
                ('footer', models.TextField(default='', verbose_name='Футер')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.personaldata', verbose_name='Личные данные')),
                ('icons', models.ManyToManyField(to='main.MenuIcon', verbose_name='Иконки меню')),
            ],
            options={
                'verbose_name': 'Настройки главной страницы',
                'verbose_name_plural': 'Настройки главной страницы',
            },
        ),
    ]
