# Generated by Django 4.0.1 on 2022-01-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='about',
        ),
        migrations.AddField(
            model_name='page',
            name='about',
            field=models.ManyToManyField(to='main.PersonalData', verbose_name='Личные данные'),
        ),
    ]
